spring.application.name=Project_Product_Catalog

server.port=8075

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG

spring.profiles.active=test
spring.autoconfigure.exclude=org.springframework.boot.webmvc.autoconfigure.error.ErrorMvcAutoConfiguration

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8089/realms/product-catalog